### ISSUE TITLE
Shows the game as full even if you are one of the players

### ISSUE THREAD

**Issue by anyaeats160carrots** [mikeyamadeo/catan-node-server#38]
Once the game has 4 players, it shows it as full and doesn't let you join even if you're one of these players

**Comment by anyaeats160carrots** [comment]
Just saw that this does not always happen

**Comment by anyaeats160carrots** [comment]
This might be a result of errors

**Comment by bipvanwinkle** [comment]
一定

**Comment by anyaeats160carrots** [comment]
Not fixed =(
![screen shot 2015-04-01 at 10 06 58 am](https://cloud.githubusercontent.com/assets/7935816/6945444/fffbc18c-d856-11e4-9c78-aa03d3699b96.png)

**Comment by anyaeats160carrots** [comment]
I am re-opening it, because even though we found out it's because of missing PlayerId's in game in mongo, I still get some games created like that. Even after dropping the db "the right way". Yesterday I had the first game w/o Ids, and the second one I created had them. TAs had this issue too.
